import { PERMISSIONS as P, ALL_PERMISSIONS, type Permission } from './permissions';

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  CLINIC_ADMIN: 'CLINIC_ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  NURSE: 'NURSE',
  ACCOUNTANT: 'ACCOUNTANT',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  PATIENT: 'PATIENT',
  MR: 'MR',
  PHARMACY_PARTNER: 'PHARMACY_PARTNER',
  LAB_PARTNER: 'LAB_PARTNER',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

const CLINICAL_READ: Permission[] = [
  P.PATIENTS_VIEW, P.PATIENTS_MEDICAL_VIEW, P.CONSULTATION_VIEW,
  P.PRESCRIPTION_VIEW, P.LAB_REPORT_VIEW, P.DOCUMENTS_VIEW,
];

/** Default permission grants per system role. Tenants may clone + customise. */
export const ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  ORG_ADMIN: ALL_PERMISSIONS.filter(
    (p) => p !== P.PLATFORM_ADMIN && p !== P.FEATURE_FLAGS_MANAGE,
  ),

  CLINIC_ADMIN: [
    P.CLINIC_VIEW, P.LOCATION_MANAGE,
    P.PATIENTS_VIEW, P.PATIENTS_CREATE, P.PATIENTS_EDIT,
    P.DOCTORS_VIEW, P.DOCTORS_MANAGE, P.STAFF_VIEW, P.STAFF_MANAGE,
    P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_EDIT, P.APPOINTMENTS_CANCEL,
    P.SCHEDULE_MANAGE, P.QUEUE_VIEW, P.QUEUE_MANAGE,
    P.CONSULTATION_VIEW, P.PRESCRIPTION_VIEW,
    P.LAB_REPORT_VIEW, P.PHARMACY_ORDER_VIEW,
    P.DOCUMENTS_VIEW, P.DOCUMENTS_UPLOAD,
    P.PAYMENT_VIEW, P.PAYMENT_CREATE, P.PAYMENT_REFUND,
    P.INVOICE_VIEW, P.INVOICE_CREATE, P.EXPENSE_MANAGE, P.EXPENSE_APPROVE,
    P.ATTENDANCE_VIEW, P.ATTENDANCE_MANAGE, P.LEAVE_VIEW, P.LEAVE_APPROVE,
    P.PAYROLL_VIEW, P.PAYROLL_MANAGE, P.PAYROLL_APPROVE,
    P.MESSAGES_VIEW, P.NOTIFICATIONS_MANAGE, P.COMMUNICATION_LOG,
    P.REPORT_VIEW, P.REPORT_EXPORT, P.AUDIT_VIEW, P.SETTINGS_MANAGE,
    P.REVIEW_MODERATE,
  ],

  DOCTOR: [
    P.CLINIC_VIEW,
    P.PATIENTS_VIEW, P.PATIENTS_CREATE, P.PATIENTS_EDIT, P.PATIENTS_MEDICAL_VIEW,
    P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_EDIT, P.APPOINTMENTS_CANCEL,
    P.SCHEDULE_MANAGE, P.QUEUE_VIEW, P.QUEUE_MANAGE,
    P.CONSULTATION_VIEW, P.CONSULTATION_CREATE, P.CONSULTATION_COMPLETE,
    P.PRESCRIPTION_VIEW, P.PRESCRIPTION_CREATE, P.PRESCRIPTION_SHARE,
    P.ADVICE_SEND, P.DIET_MANAGE, P.DIET_APPROVE,
    P.LAB_ORDER, P.LAB_REPORT_VIEW,
    P.DOCUMENTS_VIEW, P.DOCUMENTS_UPLOAD,
    P.PAYMENT_VIEW, P.INVOICE_VIEW, P.EXPENSE_MANAGE,
    P.MESSAGES_VIEW, P.MESSAGES_SEND,
    P.BLOG_MANAGE, P.REPORT_VIEW,
  ],

  RECEPTIONIST: [
    P.CLINIC_VIEW, P.DOCTORS_VIEW,
    P.PATIENTS_VIEW, P.PATIENTS_CREATE, P.PATIENTS_EDIT,
    P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_EDIT, P.APPOINTMENTS_CANCEL,
    P.QUEUE_VIEW, P.QUEUE_MANAGE,
    P.DOCUMENTS_VIEW, P.DOCUMENTS_UPLOAD,
    P.PAYMENT_VIEW, P.PAYMENT_CREATE, P.INVOICE_VIEW, P.INVOICE_CREATE,
    P.COMMUNICATION_LOG, P.MESSAGES_VIEW,
  ],

  NURSE: [
    P.CLINIC_VIEW, P.DOCTORS_VIEW,
    ...CLINICAL_READ,
    P.APPOINTMENTS_VIEW, P.QUEUE_VIEW, P.QUEUE_MANAGE,
    P.DOCUMENTS_UPLOAD, P.COMMUNICATION_LOG,
  ],

  ACCOUNTANT: [
    P.CLINIC_VIEW, P.PATIENTS_VIEW,
    P.PAYMENT_VIEW, P.PAYMENT_CREATE, P.PAYMENT_REFUND,
    P.INVOICE_VIEW, P.INVOICE_CREATE,
    P.EXPENSE_MANAGE, P.EXPENSE_APPROVE,
    P.PAYROLL_VIEW, P.PAYROLL_MANAGE,
    P.REPORT_VIEW, P.REPORT_EXPORT,
  ],

  MANAGER: [
    P.CLINIC_VIEW, P.DOCTORS_VIEW, P.STAFF_VIEW, P.STAFF_MANAGE,
    P.PATIENTS_VIEW, P.APPOINTMENTS_VIEW, P.QUEUE_VIEW,
    P.ATTENDANCE_VIEW, P.ATTENDANCE_MANAGE, P.LEAVE_VIEW, P.LEAVE_APPROVE,
    P.PAYROLL_VIEW, P.EXPENSE_MANAGE,
    P.REPORT_VIEW, P.REPORT_EXPORT, P.COMMUNICATION_LOG,
  ],

  STAFF: [P.CLINIC_VIEW, P.APPOINTMENTS_VIEW, P.QUEUE_VIEW, P.ATTENDANCE_VIEW, P.LEAVE_VIEW],

  // Patients are authorised through ownership checks, not clinic-wide grants.
  PATIENT: [
    P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_CANCEL,
    P.PRESCRIPTION_VIEW, P.LAB_REPORT_VIEW, P.DOCUMENTS_VIEW, P.DOCUMENTS_UPLOAD,
    P.PAYMENT_VIEW, P.INVOICE_VIEW, P.MESSAGES_VIEW, P.MESSAGES_SEND,
  ],

  // MR must never reach patient medical data.
  MR: [P.DOCTORS_VIEW, P.MR_LEADS_MANAGE, P.MR_ONBOARDING_MANAGE, P.REPORT_VIEW],

  PHARMACY_PARTNER: [
    P.PHARMACY_ORDER_VIEW, P.PHARMACY_ORDER_MANAGE, P.PHARMACY_INVENTORY_MANAGE,
    P.PAYMENT_VIEW, P.MESSAGES_VIEW,
  ],

  LAB_PARTNER: [
    P.LAB_REPORT_VIEW, P.LAB_REPORT_UPLOAD, P.DOCUMENTS_UPLOAD,
    P.PAYMENT_VIEW, P.MESSAGES_VIEW,
  ],
};

/** Roles whose scope is a single patient / partner org rather than a clinic. */
export const NON_CLINIC_ROLES: SystemRole[] = [
  SYSTEM_ROLES.PATIENT,
  SYSTEM_ROLES.MR,
  SYSTEM_ROLES.PHARMACY_PARTNER,
  SYSTEM_ROLES.LAB_PARTNER,
];

export const LOGIN_PORTALS = {
  admin: [SYSTEM_ROLES.SUPER_ADMIN, SYSTEM_ROLES.ORG_ADMIN],
  portal: [
    SYSTEM_ROLES.CLINIC_ADMIN, SYSTEM_ROLES.DOCTOR, SYSTEM_ROLES.RECEPTIONIST,
    SYSTEM_ROLES.NURSE, SYSTEM_ROLES.ACCOUNTANT, SYSTEM_ROLES.MANAGER, SYSTEM_ROLES.STAFF,
  ],
  patient: [SYSTEM_ROLES.PATIENT],
  mr: [SYSTEM_ROLES.MR],
  pharmacy: [SYSTEM_ROLES.PHARMACY_PARTNER],
  lab: [SYSTEM_ROLES.LAB_PARTNER],
} as const satisfies Record<string, readonly SystemRole[]>;

export type LoginPortal = keyof typeof LOGIN_PORTALS;
